version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    container_name:
      zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    container_name:
      kafka
    restart: always
    volumes:
      - ./kafka/data:/bitnami/kafka
    networks:
      - app-tier
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LOG_RETENTION_BYTES=1073741824
    depends_on:
      - zookeeper

  spring:
    build:
      context: .
      args:
        - JAR_FILE=build/libs/*.jar
    container_name:
      spring
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - kafka

  db:
    image: mysql
    container_name:
      mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Anton050
    networks:
      - app-tier
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name:
      adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-tier
